name: auth_service
description: Flutter Package that provides complete code for email authentication using Firebase
version: 0.0.1

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_core_platform_interface: 4.5.2

dev_dependencies:
  flutter_lints: ^2.0.1
