//PRODUCT
export const GETPRODUCT_START = 'GETPRODUCT_START'
export const GETPRODUCT_SUCCESS = 'GETPRODUCT_SUCCESS'
export const GETPRODUCT_FAIL = 'GETPRODUCT_FAIL'
export const ADDRESOURCE_START = 'ADDRESOURCE_START'
export const ADDRESOURCE_SUCCESS = 'ADDRESOURCE_SUCCESS'
export const ADDRESOURCE_FAIL = 'ADDRESOURCE_FAIL'