name: CI/CD Workflow [DEV] - Deploys Flutter Web App to DEV Env

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events only for the "develop" branch
  pull_request: 
    branches:
      - develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Get project's code from branch
      - name: Checkout branch
        uses: actions/checkout@v3

      # Build Flutter Web App (User side)
      - name: Build Flutter Web App
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
        run: |
          flutter pub get
          flutter build web --web-renderer canvaskit

      # Build Flutter Web App (Admin side)
      - name: Build Flutter Web App
        uses: subosito/flutter-action@v2
        working-directory: ./admin_panel
        with:
          flutter-version: '3.0.5'
          channel: 'stable'
        run: |
          flutter pub get
          flutter build web --web-renderer canvaskit

      # Deploy Web & Admin applications to Firebase Hosting
      - name: Deploy to Firebase Hosting DEV
        uses: FirebaseExtended/action-hosting-deploy@v0
        working-directory: ./
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_FIREBASE_HOSTING_DEV_SA_KEY }}"
          projectId: qrlink-dev
          channelId: live
