name: CI/CD Workflow [PROD] - Deploys Flutter Web & Admin Apps to PROD Env

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events only for the "develop" branch
  pull_request: 
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Get project's code from branch
      - name: Checkout branch
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.5'
          channel: 'stable'

      - name: Build ADMIN app
        working-directory: ./admin_panel
        run: |
          flutter pub get
          flutter build web --web-renderer canvaskit
      
      - name: Build USER app
        working-directory: ./
        run: |
          flutter pub get
          flutter build web --web-renderer canvaskit

      # Deploy Web & Admin applications to Firebase Hosting
      - name: Deploy to Firebase Hosting DEV
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.GCP_FIREBASE_HOSTING_PROD_SA_KEY }}"
          args: deploy --only hosting --project prod
          projectId: qrlink-dev
          channelId: live
